title: Daily Data Analysis of Coronavirus COVID19 Curve for US
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "show_exerpts:"
  Daily data analysis of coronavirus COVID-19 data.

# It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /covid-curve

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: covid-curve
  tagline: Concerned Datascientists
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: true

  # generate social links in footer
  social_links:
    #twitter: thelehhman
    github:  jacobfulano
    #linkedIn: in/thelehhman
    rss: rss


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
